### PR TITLE
Adds the option to choose the mouse pointer theme for the Login Window

### PR DESCRIPTION
**Pull request by claudiux**
I propose to add an option to choose the mouse pointer theme for the Login Window.

Login Window with the selected Mouse Pointer theme:
Login_Window

Login Window Settings with selected Mouse Pointer theme:
Login_Window_Settings1

Login Window Settings with all Mouse Pointer themes:
Login_Window_Settings2

I hope this will suit you.

Best regards.
Claudiux

### CODE REVIEW

**Comment by claudiux** [comment]
To try this feature, I have installed the packages: `chameleon-cursor-theme` `oxygen-cursor-theme` `oxygen-cursor-theme-extra`.

(My father is a partially sighted person. He did not see the mouse cursor on the login window. That's what gave me the idea to add this missing option.)

**Comment by claudiux** [comment]
@clefebvre Should I change something?

**Comment by claudiux** [comment]
Will this option be integrated in Cinnamon 4.4? Should I make changes?

**Comment by clefebvre** [comment]
Thanks @claudiux and sorry for the delay. There are a few things which aren't OK but I'll address them in master. This is a cool feature :)

**Comment by claudiux** [comment]
Many thanks, @clefebvre ! If you have the time to tell me which things are not OK...

**Comment by clefebvre** [comment]
Ah sorry @claudiux, I didn't want to ask you for changes considering it took me so long to review it. I merged it and addressed the issues (which are very small) in https://github.com/linuxmint/lightdm-settings/commit/45413ec4c95fa10b69d8c267c7e82ab6c91a7d64.

I can explain the gettext thing a little bit if you want. This is an XApp project so it's cross-distro but also cross-DE. We cannot depend, rely or even assume the presence of Cinnamon.

**Pull request merged**
