### PR TITLE
Migrate to python-xapp controls - UI interface

### PR DESCRIPTION
**Pull request by ghost**
An initial approach on porting LightDM Settings from it's current UI to a new one based on XApp, this may be a little mock-up if you wish or you can use it for future references, this is based on the UI from mintdesktop

Feel free to check if this may work or if it is functional to you, as of now I am still trying to understand and work on the code (or if I should remove or add something considering the mintdesktop UI file base)

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
My apologies, it seems that by pushing to the same branch on my fork added more information and more things to check (breaking your "1 pull request per change only), I am still "removing the oxide" and polishing some git usage here

I added the initial interface in the code so you can test it with the previous commit, since I got stuck trying to "port" the rest of the code and I don't know how some of this new control works, I leave it up to you to add the rest to test, while I try to study the python-xapp code

**EDIT:** I have manage to at least port many of the things existing into dconf so far (lightdm conf file is the one I am studying so far), but I don't push into my branch yet because that will add more commits, if you are ok with this I can pull the other changes I have performed so far

**Comment by clefebvre** [comment]
Thanks @SamBurgos, I'll mark it as Next for now so it targets the next release. I'll be able to help with this and merge it during the start of the next cycle.

**Comment by mtwebster** [comment]
Hi, it looks as though some similar changes got implemented between the time you opened this and now, and this won't apply - and I apologize, this shouldn't have happened without a bit more consideration.  If you're interested, it looks like it could still be ported to use the common widgets, just the more consistent layout is already there.

**Comment by ghost** [comment]
Understood, let me know if there is anything else I can do to check this, otherwise, feel free to close it and I will start anew

**Pull request closed without merging**
